### PR TITLE
Added phrase as identical to contains except for string phrases.

### PR DESCRIPTION
**Pull request by oligus**
Was lacking exact phrases, ie field:"this is a phrase".

### CODE REVIEW

**Comment by dewos** [comment]
@oligus right now the API are 1:1 with Spring Criteria, I'm unsure that fork it is a good idea. You could use ->is() with escaping, right?

**Comment by oligus** [comment]
Thank you for your reply, perhaps I'm doing it wrong. The issue is with multivalued field with multiple items that are separated by "|":

`"list":["ABC|HJ34545945", "ABC|ER10435517", "CDE|ED19345928", "CDE|FE33348050"]`

`->is()` yields `list:CDE|ED19345928` and will match all records with CDE in it

`->phrase()` yields `list:"CDE|ED19345928"` and will match records with the correct id only (1 record in this case)

Again, I might be mistaken but putting '"' around the phrase solved this particular issue for me. I could not get it to work with the escaping, it returned same results as `->is()`, that is all records that match the first item not the whole phrase.

**Comment by dewos** [comment]
@oligus ah yes, you shold try with ->expression() then, it is a raw "catch-all" method without escaping.

**Comment by oligus** [comment]
Aha! I totally missed that one, that makes alot of sense and works perfectly, thanks. Sorry for the confusion, I guess you can just decline this PR :-) Thanks again.

**Comment by dewos** [comment]
@oligus any time 👍

**Pull request closed without merging**
